name: Like
main: me.endorphin8er.Rater.Rate
version: 1.4.1
depend: [Spout]
authors: [endorphin8er,Quantum-Sicarius,Guy_de_Siguro]
commands:
   like:
      usage: /<command>
   dislike:
      usage: /<command>
   agree:
      usage: /<command>
   disagree:
      usage: /<command>
   facepalm:
      usage: /<command>
